import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import * as T from 'three';
import {encodeChunk} from '../scripts/world-format.mjs';
import {decodeChunk} from '../dist/world-format.js';
import {CollisionMap} from '../dist/driving-physics.js';
import {createPhysicsCompiler} from '../scripts/compile-physics.mjs';
import {disposeChunk,worldMetrics,decodeWorldResponse} from '../dist/world-loader.js';
import {gzipSync} from 'node:zlib';

const material=new T.MeshStandardMaterial(),geometry=new T.BoxGeometry(4,8,6);
geometry.setAttribute('cityBase',new T.BufferAttribute(new Float32Array(geometry.attributes.position.count).fill(27),1));
const mesh=new T.Mesh(geometry,material);mesh.position.set(4,9,-7);mesh.userData={layer:'buildings',spans:[{end:12,r:{id:123,source:'levels'}}]};
const instance=new T.InstancedMesh(geometry,material,2);
instance.setMatrixAt(0,new T.Matrix4().makeTranslation(500,12,800));instance.setMatrixAt(1,new T.Matrix4().makeScale(2,3,4));instance.computeBoundingSphere();
const physics=createPhysicsCompiler();
physics.addBuilding({outer:[[0,0],[20,0],[20,20],[0,20],[0,0]],holes:[[[5,5],[15,5],[15,15],[5,15],[5,5]]]},3,12);
physics.addWater({outer:[[30,0],[40,0],[40,10],[30,10],[30,0]],holes:[]},2);
physics.addRoad({id:17,tags:{highway:'residential',gameWidth:6.4,gameOneway:'-1'},geometry:[{lat:47.02,lon:28.83},{lat:47.021,lon:28.831}]});
const source={obstacles:physics.obstacles,streets:physics.streets};
const bytes=encodeChunk([mesh,instance],source,()=>0);
assert.deepEqual(new Uint8Array(await decodeWorldResponse(new Response(gzipSync(bytes)))),new Uint8Array(bytes),'static host raw gzip');
assert.deepEqual(new Uint8Array(await decodeWorldResponse(new Response(bytes,{headers:{'Content-Encoding':'gzip'}}))),new Uint8Array(bytes),'Fetch already decompressed HTTP gzip');
assert.deepEqual(bytes,encodeChunk([mesh,instance],source,()=>0),'deterministic chunk encoding');
const arrayBuffer=bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),loaded=decodeChunk(arrayBuffer,[material]);
for(const m of loaded.meshes)for(const [key,a] of Object.entries(geometry.attributes))assert.deepEqual(m.geometry.attributes[key].array,a.array,key);
assert.deepEqual(loaded.meshes[0].matrix.elements,mesh.matrix.elements);
assert.deepEqual(loaded.meshes[0].userData,mesh.userData);
assert.deepEqual(loaded.meshes[1].instanceMatrix.array,instance.instanceMatrix.array);
assert.ok(loaded.meshes[1].instanceMatrix.isInstancedBufferAttribute,'GPU instance divisor preserved');
assert.deepEqual(loaded.meshes[1].boundingSphere,instance.boundingSphere);
assert.deepEqual(loaded.meshes[0].geometry.index.array,geometry.index.array);
assert.equal(loaded.meshes[0].geometry,loaded.meshes[1].geometry,'shared geometry');
const collisions=new CollisionMap();for(const p of loaded.physics.obstacles)collisions.add(p);
assert.equal(collisions.blocked(2,2,.1,4),true);
assert.equal(collisions.blocked(10,10,.1,4),false,'courtyard retained');
assert.equal(collisions.blocked(2,2,.1,15),false,'height separation retained');
assert.equal(collisions.blocked(35,5,.1,0),true);
assert.equal(collisions.blocked(35,5,.1,7),false,'bridge above water remains driveable');
assert.equal(loaded.physics.streets[0].width,6.4);assert.ok(loaded.physics.streets[0].oneway);
assert.ok(loaded.physics.streets[0].a[0]>loaded.physics.streets[0].b[0],'reverse one-way retained');
assert.throws(()=>decodeChunk(arrayBuffer.slice(0,10),[material]));
assert.throws(()=>decodeChunk(arrayBuffer,[]));
let geometryDisposals=0,instanceDisposals=0,materialDisposals=0;
loaded.meshes[0].geometry.addEventListener('dispose',()=>geometryDisposals++);
loaded.meshes[1].addEventListener('dispose',()=>instanceDisposals++);
material.addEventListener('dispose',()=>materialDisposals++);
const group=new T.Group();group.add(...loaded.meshes);disposeChunk(loaded);
assert.equal(group.children.length,0);assert.equal(geometryDisposals,1);assert.equal(instanceDisposals,1);
assert.equal(materialDisposals,0,'shared materials survive eviction');assert.equal(worldMetrics.disposedChunks,1);
// Enforce the architectural boundary across the entire runtime import graph.
const visited=new Set();
async function inspect(file){if(visited.has(file))return;visited.add(file);const text=await fs.readFile(new URL('../dist/'+file,import.meta.url),'utf8');assert.ok(!/fetch\(['"]\.\/data\//.test(text),'source-data fetch in runtime '+file);assert.ok(!/new (?:THREE|T)\.(?:ExtrudeGeometry|ShapeGeometry)/.test(text),'map triangulation in runtime '+file);for(const m of text.matchAll(/from ['"]\.\/([^'"]+)['"]/g))if(!m[1].startsWith('vendor/'))await inspect(m[1]);}
await inspect('app.js');
console.log('Compiled world: binary attributes, instancing, picking, collision heights/holes, one-way roads, corruption checks and runtime boundary passed.');
