<?xml version="1.0" encoding="UTF-8"?><xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:maps="https://geodata.gov.md/geoserver/maps/" xmlns:wfs="http://www.opengis.net/wfs/2.0" elementFormDefault="qualified" targetNamespace="https://geodata.gov.md/geoserver/maps/">
  <xsd:import namespace="http://www.opengis.net/gml/3.2" schemaLocation="https://geodata.gov.md/geoserver/schemas/gml/3.2.1/gml.xsd"/>
  <xsd:complexType name="lm17_line_road_edgeType">
    <xsd:complexContent>
      <xsd:extension base="gml:AbstractFeatureType">
        <xsd:sequence>
          <xsd:element maxOccurs="1" minOccurs="0" name="geom" nillable="true" type="gml:MultiCurvePropertyType"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="gid" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="shape_leng" nillable="true" type="xsd:double"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="layer" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="medium" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="z" nillable="true" type="xsd:double"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="layer_name" nillable="true" type="xsd:string"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:element name="lm17_line_road_edge" substitutionGroup="gml:AbstractFeature" type="maps:lm17_line_road_edgeType"/>
  <xsd:complexType name="lm17_line_curbType">
    <xsd:complexContent>
      <xsd:extension base="gml:AbstractFeatureType">
        <xsd:sequence>
          <xsd:element maxOccurs="1" minOccurs="0" name="geom" nillable="true" type="gml:MultiCurvePropertyType"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="gid" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="shape_leng" nillable="true" type="xsd:double"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="layer" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="medium" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="z" nillable="true" type="xsd:double"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="layer_name" nillable="true" type="xsd:string"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:element name="lm17_line_curb" substitutionGroup="gml:AbstractFeature" type="maps:lm17_line_curbType"/>
  <xsd:complexType name="lm17_line_sidewalk_outer_edgeType">
    <xsd:complexContent>
      <xsd:extension base="gml:AbstractFeatureType">
        <xsd:sequence>
          <xsd:element maxOccurs="1" minOccurs="0" name="geom" nillable="true" type="gml:MultiCurvePropertyType"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="gid" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="shape_leng" nillable="true" type="xsd:double"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="layer" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="medium" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="z" nillable="true" type="xsd:double"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="layer_name" nillable="true" type="xsd:string"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:element name="lm17_line_sidewalk_outer_edge" substitutionGroup="gml:AbstractFeature" type="maps:lm17_line_sidewalk_outer_edgeType"/>
  <xsd:complexType name="lm17_area_roof_areaType">
    <xsd:complexContent>
      <xsd:extension base="gml:AbstractFeatureType">
        <xsd:sequence>
          <xsd:element maxOccurs="1" minOccurs="0" name="geom" nillable="true" type="gml:MultiSurfacePropertyType"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="gid" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="layer" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="z" nillable="true" type="xsd:double"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="medium" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="layer_name" nillable="true" type="xsd:string"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:element name="lm17_area_roof_area" substitutionGroup="gml:AbstractFeature" type="maps:lm17_area_roof_areaType"/>
  <xsd:complexType name="lm17_area_bridge_areaType">
    <xsd:complexContent>
      <xsd:extension base="gml:AbstractFeatureType">
        <xsd:sequence>
          <xsd:element maxOccurs="1" minOccurs="0" name="geom" nillable="true" type="gml:MultiSurfacePropertyType"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="gid" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="layer" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="z" nillable="true" type="xsd:double"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="medium" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="layer_name" nillable="true" type="xsd:string"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:element name="lm17_area_bridge_area" substitutionGroup="gml:AbstractFeature" type="maps:lm17_area_bridge_areaType"/>
  <xsd:complexType name="lm17_point_lamp_postType">
    <xsd:complexContent>
      <xsd:extension base="gml:AbstractFeatureType">
        <xsd:sequence>
          <xsd:element maxOccurs="1" minOccurs="0" name="geom" nillable="true" type="gml:MultiPointPropertyType"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="gid" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="layer" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="z" nillable="true" type="xsd:double"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="medium" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="layer_name" nillable="true" type="xsd:string"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:element name="lm17_point_lamp_post" substitutionGroup="gml:AbstractFeature" type="maps:lm17_point_lamp_postType"/>
  <xsd:complexType name="lm17_line_pedestrian_crossingType">
    <xsd:complexContent>
      <xsd:extension base="gml:AbstractFeatureType">
        <xsd:sequence>
          <xsd:element maxOccurs="1" minOccurs="0" name="geom" nillable="true" type="gml:MultiCurvePropertyType"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="gid" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="shape_leng" nillable="true" type="xsd:double"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="layer" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="medium" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="z" nillable="true" type="xsd:double"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="layer_name" nillable="true" type="xsd:string"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:element name="lm17_line_pedestrian_crossing" substitutionGroup="gml:AbstractFeature" type="maps:lm17_line_pedestrian_crossingType"/>
  <xsd:complexType name="lm17_point_traffic_signal_lightType">
    <xsd:complexContent>
      <xsd:extension base="gml:AbstractFeatureType">
        <xsd:sequence>
          <xsd:element maxOccurs="1" minOccurs="0" name="geom" nillable="true" type="gml:MultiPointPropertyType"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="gid" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="layer" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="z" nillable="true" type="xsd:double"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="medium" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="layer_name" nillable="true" type="xsd:string"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:element name="lm17_point_traffic_signal_light" substitutionGroup="gml:AbstractFeature" type="maps:lm17_point_traffic_signal_lightType"/>
  <xsd:complexType name="lm17_point_spot_height_peakType">
    <xsd:complexContent>
      <xsd:extension base="gml:AbstractFeatureType">
        <xsd:sequence>
          <xsd:element maxOccurs="1" minOccurs="0" name="geom" nillable="true" type="gml:MultiPointPropertyType"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="gid" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="layer" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="z" nillable="true" type="xsd:double"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="medium" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="layer_name" nillable="true" type="xsd:string"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:element name="lm17_point_spot_height_peak" substitutionGroup="gml:AbstractFeature" type="maps:lm17_point_spot_height_peakType"/>
  <xsd:complexType name="lm17_line_traffic_lane_areaType">
    <xsd:complexContent>
      <xsd:extension base="gml:AbstractFeatureType">
        <xsd:sequence>
          <xsd:element maxOccurs="1" minOccurs="0" name="geom" nillable="true" type="gml:MultiCurvePropertyType"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="gid" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="shape_leng" nillable="true" type="xsd:double"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="layer" nillable="true" type="xsd:long"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="medium" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="z" nillable="true" type="xsd:double"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="layer_name" nillable="true" type="xsd:string"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:element name="lm17_line_traffic_lane_area" substitutionGroup="gml:AbstractFeature" type="maps:lm17_line_traffic_lane_areaType"/>
</xsd:schema>
