import {yieldToBrowser} from '../dist/loading.js';
import {addSurfaceBatches} from '../dist/surface-batches.js';
import {roadTags,roadPositions,roadProfile} from '../dist/road-model.js';
import * as THREE from 'three';
import {waterHeight,heightAt,roadHeight,buildingBase,drapeGeometry,bridgeStructure,terrainProfile} from '../dist/terrain.js';
import {roadWidth,roofHeight,roofGeometry,laneGeometry} from '../dist/realism.js';
import {buildingStyle} from '../dist/facades.js';
import {mergeGeometries} from '../dist/vendor/BufferGeometryUtils.js';
import {area,estimate,polygons} from '../dist/model.js';

export function createCityCompiler(driving,realismData,lod){
const buildings=new THREE.Group(),greens=new THREE.Group(),roads=new THREE.Group();
const material=new THREE.MeshStandardMaterial({vertexColors:true,roughness:.85,metalness:0,side:THREE.DoubleSide});
material.userData.cityShader='facade';
const parkMat=new THREE.MeshStandardMaterial({color:'#385a4d',roughness:1,side:THREE.DoubleSide}),waterMat=new THREE.MeshStandardMaterial({color:'#3b8391',roughness:.45,metalness:.2,side:THREE.DoubleSide});
const streetMat=new THREE.MeshStandardMaterial({color:'#ffffff',side:THREE.DoubleSide,vertexColors:true,roughness:1}),pathMat=streetMat.clone();
streetMat.userData.cityShader=pathMat.userData.cityShader='road';
const seen=new Set(),records=[],pickables=[],chunks=[];let totalMapped=0;
function shape(poly){const s=new THREE.Shape(poly.outer.map(p=>new THREE.Vector2(p[0],-p[1])));for(const h of poly.holes)s.holes.push(new THREE.Path(h.map(p=>new THREE.Vector2(p[0],-p[1]))));return s;}
function colorFor(r){const mode='material';if(mode==='source')return new THREE.Color({height:'#6bdcba',levels:'#73a9ef',estimate:'#ddb274'}[r.source]);if(mode==='height')return new THREE.Color().setHSL(.52-Math.min(r.height/110,1)*.48,.57,.57);return new THREE.Color().setHSL(.1+(r.id%7)*.004,.17,.65+(r.id%5)*.025);}
function applyColors(g,r){const c=colorFor(r),n=g.getAttribute('position').count,colors=new Float32Array(n*3);const normals=g.getAttribute('normal');for(let i=0;i<n;i++){const shade=normals.getY(i)>.6?1.1:.83;colors[i*3]=c.r*shade;colors[i*3+1]=c.g*shade;colors[i*3+2]=c.b*shade;}g.setAttribute('color',new THREE.BufferAttribute(colors,3));g.setAttribute('cityType',new THREE.BufferAttribute(new Float32Array(n).fill(buildingStyle(r.tags)),1));g.setAttribute('cityBase',new THREE.BufferAttribute(new Float32Array(n).fill(r.base||0),1));}
function flush(batch){if(!batch.length)return;let end=0;const spans=batch.map(b=>({end:end+=b.g.attributes.position.count/3,r:b.r}));const g=mergeGeometries(batch.map(b=>b.g),false);if(!g)return;const mesh=new THREE.Mesh(g,material);mesh.userData.spans=spans;buildings.add(mesh);pickables.push(mesh);chunks.push(mesh);batch.forEach(b=>b.g.dispose());batch.length=0;}
function roadRecord(e,t,osmTags){const p=terrainProfile(e.id),model=roadProfile(e.id),points=p?.points||[];return {kind:p?.bridge?'bridge':'road',id:e.id,type:e.type,tags:osmTags,derived:{width_m:roadWidth(t),model_lanes:model?.lanes??null,oneway:t.gameOneway??null,road_profile:p?{bridge:!!p.bridge,point_count:points.length,min_relative_y_m:Math.min(...points.map(q=>q[2])),max_relative_y_m:Math.max(...points.map(q=>q[2]))}:null}};}
function roadGeometry(e){const t=e.tags,pos=roadPositions(e,roadWidth(t));const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));const tint=new THREE.Color(({'asphalt':'#667378','paving_stones':'#a09b8c','gravel':'#928979','unpaved':'#8f7a5a','ground':'#827155','dirt':'#827155','concrete':'#a5aaa4'})[t.surface]||(/footway|path|steps/.test(t.highway)?'#64796e':'#69767b'));const colors=new Float32Array(pos.length);for(let i=0;i<colors.length;i+=3){colors[i]=tint.r;colors[i+1]=tint.g;colors[i+2]=tint.b;}g.setAttribute('color',new THREE.BufferAttribute(colors,3));g.setAttribute('roadSurface',new THREE.BufferAttribute(new Float32Array(pos.length/3).fill(t.surface==='paving_stones'?1:0),1));return g;}
async function ingest(data){if(!Array.isArray(data.elements))throw new Error('Invalid map data');const batches=new Map(),roadG=[],pathG=[],parkG=[],waterG=[],laneG=[];const members=new Set();for(const e of data.elements)if(e.type==='relation'&&e.tags?.building)for(const m of e.members||[])members.add('way/'+m.ref);
let yieldStart=performance.now();for(const e of data.elements){const key=e.type+'/'+e.id,osmTags={...(e.tags||{}),...(realismData.extra[e.id]||{})},t=roadTags(e.id,osmTags);e.tags=t;if(seen.has(key))continue;seen.add(key);if(t.building&&t.building!=='no'&&!members.has(key)&&t.location!=='underground'&&t.layer!=='-1'){for(const p of polygons(e)){const a=area(p.outer)-p.holes.reduce((s,h)=>s+area(h),0);if(a<3)continue;const est=estimate(t,a);driving.addBuilding(p,est.minHeight,est.height);const r={kind:'building',id:e.id,type:e.type,tags:osmTags,area:a,...est};const rh=Math.max(0,Math.min(roofHeight(t,est.height),est.height-est.minHeight-.5));let g=new THREE.ExtrudeGeometry(shape(p),{depth:est.height-est.minHeight-rh,bevelEnabled:false,steps:1,curveSegments:1});g.rotateX(-Math.PI/2);g.translate(0,est.minHeight+.2,0);if(rh){const roof=roofGeometry(p,est.height-rh+.2,rh,t['roof:shape']);const merged=mergeGeometries([g,roof],false);if(merged){g.dispose();roof.dispose();g=merged;}}const base=buildingBase(p);r.base=base;const low=Math.min(...p.outer.map(p=>heightAt(...p)));if(base-low>.3){const foundation=new THREE.ExtrudeGeometry(shape(p),{depth:base-low,bevelEnabled:false,steps:1});foundation.rotateX(-Math.PI/2);foundation.translate(0,low-base,0);const merged=mergeGeometries([g,foundation],false);if(merged){g.dispose();foundation.dispose();g=merged;}}g.translate(0,base,0);applyColors(g,r);lod?.building(p,r);const cell=Math.floor(p.outer[0][0]/500)+','+Math.floor(p.outer[0][1]/500);if(!batches.has(cell))batches.set(cell,[]);const batch=batches.get(cell);batch.push({g,r});records.push(r);if(est.source!=='estimate')totalMapped++;if(batch.length>=128)flush(batch);}}
else if((t.highway||t.waterway)&&!t.gameHidden&&e.geometry?.length>1){const record=t.highway?roadRecord(e,t,osmTags):{kind:'waterway',id:e.id,type:e.type,tags:t,derived:{}};if(t.highway){const structure=bridgeStructure(e.id);if(structure){structure.traverse(m=>{if(m.isMesh)m.userData.feature=record;});roads.add(structure);}driving.addRoad(e);lod?.road(e,record);const lg=laneGeometry(e);if(lg)laneG.push(drapeGeometry(lg,(x,z)=>roadHeight(x,z,e.id),12));}(t.waterway||/footway|path|cycleway|steps/.test(t.highway)?pathG:roadG).push({geometry:drapeGeometry(roadGeometry(e),(x,z)=>roadHeight(x,z,e.id),12),record});}
else if(/^(water|wood|scrub|grassland)$/.test(t.natural)||/^(park|garden|recreation_ground)$/.test(t.leisure)||/^(forest|grass|recreation_ground|cemetery)$/.test(t.landuse)){for(const p of polygons(e)){if(t.natural==='water')driving.addWater(p,waterHeight(e.id,p));lod?.surface(p,t.natural==='water'?waterHeight(e.id,p):null);let g=new THREE.ShapeGeometry(shape(p));g.rotateX(-Math.PI/2);g.translate(0,t.natural==='water'?.05:0,0);if(t.natural==='water')g.translate(0,waterHeight(e.id,p),0);else g=drapeGeometry(g,heightAt,45);(t.natural==='water'?waterG:parkG).push(g);}}
if(performance.now()-yieldStart>10){await yieldToBrowser();yieldStart=performance.now();}}
for(const batch of batches.values())flush(batch);if(laneG.length)addSurfaceBatches(roads,laneG,new THREE.MeshStandardMaterial({color:'#d8d6c2',side:THREE.DoubleSide,roughness:1}));for(const [list,mat] of [[parkG,parkMat],[waterG,waterMat]])if(list.length)addSurfaceBatches(greens,list,mat);for(const [list,mat] of [[roadG,streetMat],[pathG,pathMat]])if(list.length)addSurfaceBatches(roads,list,mat);}

return {ingest,buildings,greens,roads,records,clear(){for(const group of [buildings,greens,roads])group.clear();records.length=pickables.length=chunks.length=0;}};
}
